name: SauceDemoCI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run tests
      run: mvn clean test
    - name: Run cross browsers tests
      run: mvn clean test -DsuiteXmlFile='src/test/resources/CrossBrowserTest.xml'